# mkdocs.yml

site_name: Bootcamp dbt-core
site_description: 'Guia para construir um data warehouse moderno utilizando dbt-core e PostgreSQL na AWS.'
site_author: 'Luciano Vasconcelos'

# Configurações do tema Material
theme:
  name: 'material'
  language: 'pt'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs
  logo: 'images/logo.svg'  # Caminho para o logotipo do site (opcional)
  favicon: 'images/logo.svg'  # Caminho para o favicon (opcional)

# Configurações de navegação
nav:
  - Home: index.md
  - Guia Rápido:
      - 'Bem-vindo': guides/bem_vindo.md
      - 'Configuração Inicial': guides/guia_rapido.md
      - 'Configuração Testes': guides/testes.md
  - Conteúdo:
      - 'dbt models': reference/models.md
      - 'Projeto': reference/projeto.md
      - 'Plataformas suportadas': reference/supported_data_plarforms.md      

# Plugins
plugins:
  - search

# Configurações extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/seu-usuario/nome-do-repositorio'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/lucianovasconcelosf/'

repo_name: lvgalvao/dbt-core-northwind-project
repo_url: https://github.com/lvgalvao/dbt-core-northwind-project

# Configurações para Markdown
markdown_extensions:
  - toc:
      permalink: true
